dist: xenial
language: python
python:
  - "3.7"
cache:
  - pip
install:
  - pip install --upgrade
    ghp-import
    git+https://github.com/manubot/manubot@025b7c78e96d37cb81388bf739411dfe82969780
    pyyaml
script:
  - python process-catalog.py
after_success:
  - test $TRAVIS_BRANCH = "master" &&
    test $TRAVIS_EVENT_TYPE = "push" &&
    ghp-import
    --push --no-jekyll
    --message="Generate catalog output on $(date --iso --utc)\n\n
    built by $TRAVIS_JOB_WEB_URL\n
    based on https://github.com/$TRAVIS_REPO_SLUG/commit/$TRAVIS_COMMIT\n"
    output
