dist: bionic
language: python
python:
  - "3.8"
cache:
  - pip
install:
  - pip install --upgrade
    beautifulsoup4
    ghp-import
    git+https://github.com/manubot/manubot@0b7c14a6bbab77d6c91f0019dff524bb43587769
    pyyaml
    requests
script:
  - python process-catalog.py
deploy:
  skip_cleanup: true
  provider: script
  script: bash -o xtrace deploy.sh
  on:
    branch: master
