dist: bionic
language: python
python:
  - "3.8"
cache:
  - pip
install:
  - pip install --upgrade
    beautifulsoup4
    ghp-import
    git+https://github.com/manubot/manubot@217e51473f1fd1c6427803676b3c70d44314bb93
    pyyaml
    requests
script:
  - python process-catalog.py
deploy:
  skip_cleanup: true
  provider: script
  script: bash -o xtrace deploy.sh
  on:
    branch: master
